import { Task, Document, Template, Notification } from "@/types";

export const TASKS: Task[] = [
  {
    id: "1",
    key: "DZ-1",
    title: "CAF housing aid renewal",
    titleFr: "Renouvellement APL CAF",
    description:
      "Annual renewal of APL housing aid for current apartment. Need to submit updated income information and proof of accommodation.",
    category: "caf",
    status: "in_progress",
    deadline: "2025-02-15",
    createdAt: "2025-01-20",
    steps: [
      { id: "s1", title: "Gather income documents", desc: "Latest 3 pay slips from employer", done: true },
      { id: "s2", title: "Update accommodation proof", desc: "Current lease + latest rent receipt", done: true },
      { id: "s3", title: "Submit online on caf.fr", desc: "Complete the annual declaration form", done: false },
      { id: "s4", title: "Confirm receipt", desc: "Wait for CAF confirmation email", done: false },
    ],
    docs: ["doc1", "doc3"],
  },
  {
    id: "2",
    key: "DZ-2",
    title: "CPAM carte vitale application",
    titleFr: "Demande carte vitale CPAM",
    description:
      "First-time application for Carte Vitale after moving to France. Required for healthcare access.",
    category: "cpam",
    status: "completed",
    deadline: "2025-01-28",
    createdAt: "2025-01-05",
    steps: [
      { id: "s5", title: "Create ameli account", desc: "Register on ameli.fr", done: true },
      { id: "s6", title: "Prepare identity documents", desc: "Valid ID + proof of address", done: true },
      { id: "s7", title: "Submit application online", desc: "Upload documents and fill the form", done: true },
      { id: "s8", title: "Attend appointment", desc: "Visit CPAM office if required", done: true },
      { id: "s9", title: "Receive carte vitale", desc: "Wait for postal delivery", done: true },
    ],
    docs: ["doc2", "doc3"],
  },
  {
    id: "3",
    key: "DZ-3",
    title: "Tax declaration 2024",
    titleFr: "Déclaration fiscale 2024",
    description:
      "Annual income tax declaration for the 2024 fiscal year. Must be completed before the deadline.",
    category: "tax",
    status: "todo",
    deadline: "2025-06-05",
    createdAt: "2025-02-01",
    steps: [
      { id: "s10", title: "Collect income statements", desc: "Get all income certificates from employers", done: false },
      { id: "s11", title: "Review pre-filled declaration", desc: "Check impots.gouv.fr for pre-filled data", done: false },
      { id: "s12", title: "Submit declaration", desc: "Validate and send online", done: false },
    ],
    docs: [],
  },
  {
    id: "4",
    key: "DZ-4",
    title: "ANTS driver license renewal",
    titleFr: "Renouvellement permis ANTS",
    description:
      "Renew expired driver license through the ANTS online platform. Critical deadline approaching.",
    category: "ants",
    status: "in_progress",
    deadline: "2025-02-07",
    createdAt: "2025-01-25",
    steps: [
      { id: "s13", title: "Create ANTS account", desc: "Register on ants.gouv.fr", done: true },
      { id: "s14", title: "Upload photo and signature", desc: "Digital photo meeting specific requirements", done: true },
      { id: "s15", title: "Upload old license copy", desc: "Scan both sides of current license", done: false },
      { id: "s16", title: "Upload proof of address", desc: "Recent utility bill or rent receipt", done: false },
      { id: "s17", title: "Pay processing fee", desc: "Online payment via ANTS platform", done: false },
      { id: "s18", title: "Receive new license", desc: "Wait for production and delivery", done: false },
    ],
    docs: ["doc2"],
  },
  {
    id: "5",
    key: "DZ-5",
    title: "Prefecture appointment request",
    titleFr: "Demande de rendez-vous préfecture",
    description:
      "Book an appointment at the prefecture for titre de séjour renewal.",
    category: "prefecture",
    status: "todo",
    deadline: "2025-02-25",
    createdAt: "2025-01-28",
    steps: [
      { id: "s19", title: "Check available slots", desc: "Monitor prefecture website for openings", done: false },
      { id: "s20", title: "Prepare complete dossier", desc: "All required documents in original + copies", done: false },
      { id: "s21", title: "Attend appointment", desc: "Bring all documents to prefecture", done: false },
    ],
    docs: ["doc2", "doc5"],
  },
  {
    id: "6",
    key: "DZ-6",
    title: "CROUS student dossier",
    titleFr: "Dossier étudiant CROUS",
    description:
      "Submit social housing application through CROUS for next academic year.",
    category: "crous",
    status: "in_progress",
    deadline: "2025-03-15",
    createdAt: "2025-01-30",
    steps: [
      { id: "s22", title: "Create DSE on messervices.etudiant.gouv.fr", desc: "Complete the social file online", done: true },
      { id: "s23", title: "Submit scholarship application", desc: "Fill CROUS scholarship form if eligible", done: false },
      { id: "s24", title: "Upload supporting documents", desc: "ID, income proof, enrollment certificate", done: false },
      { id: "s25", title: "Confirm submission", desc: "Verify all documents received", done: false },
    ],
    docs: ["doc1", "doc2"],
  },
  {
    id: "7",
    key: "DZ-7",
    title: "France Travail registration",
    titleFr: "Inscription France Travail",
    description:
      "Register as a job seeker at France Travail (formerly Pôle Emploi).",
    category: "travail",
    status: "completed",
    deadline: "2025-01-15",
    createdAt: "2025-01-02",
    steps: [
      { id: "s26", title: "Create France Travail account", desc: "Register on francetravail.fr", done: true },
      { id: "s27", title: "Complete registration form", desc: "Personal info, qualifications, situation", done: true },
      { id: "s28", title: "Attend induction meeting", desc: "Scheduled appointment with advisor", done: true },
    ],
    docs: ["doc2", "doc4"],
  },
  {
    id: "8",
    key: "DZ-8",
    title: "Bank account address update",
    titleFr: "Mise à jour adresse bancaire",
    description: "Update registered address with the bank after moving.",
    category: "other",
    status: "todo",
    deadline: "2025-03-01",
    createdAt: "2025-02-01",
    steps: [
      { id: "s29", title: "Get new proof of address", desc: "Utility bill with new address", done: false },
      { id: "s30", title: "Submit change online", desc: "Use bank app or visit branch", done: false },
    ],
    docs: ["doc3"],
  },
];

export const DOCUMENTS: Document[] = [
  { id: "doc1", name: "pay_slip_december.pdf", type: "paySlip", size: "245 KB", uploadedAt: "2025-01-15", tasks: ["1", "6"] },
  { id: "doc2", name: "passport_scan.jpg", type: "idDoc", size: "1.2 MB", uploadedAt: "2025-01-10", tasks: ["2", "4", "5", "7"] },
  { id: "doc3", name: "lease_agreement.pdf", type: "proofAddress", size: "890 KB", uploadedAt: "2025-01-08", tasks: ["1", "8"] },
  { id: "doc4", name: "rib_bank_details.pdf", type: "bankDetails", size: "120 KB", uploadedAt: "2025-01-12", tasks: ["7"] },
  { id: "doc5", name: "birth_certificate.pdf", type: "civilStatus", size: "340 KB", uploadedAt: "2025-01-06", tasks: ["5"] },
  { id: "doc6", name: "tax_notice_2023.pdf", type: "taxDoc", size: "560 KB", uploadedAt: "2025-01-18", tasks: [] },
];

export const TEMPLATES: Template[] = [
  {
    id: "t1",
    title: "CAF housing aid (APL)",
    titleFr: "Aide au logement CAF (APL)",
    category: "caf",
    description: "Apply for APL housing aid through CAF. Reduces your monthly rent payment based on income and family situation.",
    icon: "home",
    steps: [
      { title: "Create CAF account", desc: "Register on caf.fr with your social security number" },
      { title: "Gather required documents", desc: "National ID, proof of address, income proof, RIB" },
      { title: "Complete online application", desc: "Fill in the housing aid form on caf.fr" },
      { title: "Submit and wait for processing", desc: "CAF typically processes within 2-4 weeks" },
    ],
    requiredDocs: ["National ID or passport", "Proof of address (less than 3 months)", "Latest 3 pay slips", "RIB (bank details)"],
    officialLink: "https://www.caf.fr",
  },
  {
    id: "t2",
    title: "CPAM carte vitale",
    titleFr: "Carte vitale CPAM",
    category: "cpam",
    description: "Apply for your carte vitale, the essential health insurance card for accessing healthcare in France.",
    icon: "heart-pulse",
    steps: [
      { title: "Create ameli account", desc: "Register on ameli.fr to access your CPAM space" },
      { title: "Prepare identity documents", desc: "Valid ID, proof of address, birth certificate if needed" },
      { title: "Submit application online", desc: "Upload all documents through ameli.fr" },
      { title: "Attend mandatory appointment", desc: "Visit CPAM office if summoned for in-person verification" },
      { title: "Receive carte vitale by mail", desc: "Delivery typically takes 2-3 weeks after approval" },
    ],
    requiredDocs: ["Valid national ID or passport", "Proof of address", "Birth certificate (if applicable)", "Proof of social security registration"],
    officialLink: "https://www.ameli.fr",
  },
  {
    id: "t3",
    title: "Tax declaration",
    titleFr: "Déclaration fiscale",
    category: "tax",
    description: "Complete your annual income tax declaration on impots.gouv.fr. The pre-filled form is usually available in April.",
    icon: "receipt",
    steps: [
      { title: "Wait for pre-filled declaration", desc: "Available in April on impots.gouv.fr" },
      { title: "Review and correct information", desc: "Verify all pre-filled income data" },
      { title: "Add missing income sources", desc: "Foreign income, freelancing, etc." },
      { title: "Claim applicable deductions", desc: "Check eligible tax credits and deductions" },
      { title: "Validate and submit", desc: "Sign electronically and send before deadline" },
    ],
    requiredDocs: ["Income tax notice from previous year", "Pay slips", "Proof of deductible expenses", "RIB for refund"],
    officialLink: "https://www.impots.gouv.fr",
  },
  {
    id: "t4",
    title: "ANTS driver license",
    titleFr: "Permis de conduire ANTS",
    category: "ants",
    description: "Apply for, renew, or replace your driver license through the ANTS online platform.",
    icon: "car",
    steps: [
      { title: "Create ANTS account", desc: "Register on ants.gouv.fr with FranceConnect" },
      { title: "Prepare digital photo", desc: "Photo meeting ANTS specifications (35x45mm)" },
      { title: "Gather required documents", desc: "Old license, ID, proof of address" },
      { title: "Complete online form", desc: "Fill in personal info and upload documents" },
      { title: "Pay processing fee", desc: "Online payment (around 25€)" },
      { title: "Receive new license by mail", desc: "Production takes approximately 1-2 weeks" },
    ],
    requiredDocs: ["Current driver license (or loss declaration)", "Valid ID", "Digital photo (ANS compliant)", "Proof of address", "Payment method"],
    officialLink: "https://ants.gouv.fr",
  },
  {
    id: "t5",
    title: "Prefecture appointment",
    titleFr: "Rendez-vous préfecture",
    category: "prefecture",
    description: "Book and prepare for a prefecture appointment for titre de séjour, naturalization, or other procedures.",
    icon: "landmark",
    steps: [
      { title: "Check required procedure", desc: "Identify the exact type of appointment needed" },
      { title: "Monitor available slots", desc: "Prefecture slots open unpredictably — check frequently" },
      { title: "Prepare complete dossier", desc: "Original documents + copies as per checklist" },
      { title: "Attend appointment on time", desc: "Bring all documents, arrive 15 min early" },
    ],
    requiredDocs: ["Valid passport or ID", "Proof of address (less than 3 months)", "Passport photos", "Specific documents per procedure type", "Stamped envelope"],
    officialLink: "https://www.prefectures.gouv.fr",
  },
  {
    id: "t6",
    title: "CROUS student dossier",
    titleFr: "Dossier étudiant CROUS",
    category: "crous",
    description: "Complete the DSE (Dossier Social Étudiant) for CROUS scholarship and/or social housing application.",
    icon: "graduation-cap",
    steps: [
      { title: "Create student account", desc: "Register on messervices.etudiant.gouv.fr" },
      { title: "Complete DSE online", desc: "Fill in personal, family, and income information" },
      { title: "Apply for scholarship if eligible", desc: "Fill the CROUS scholarship section" },
      { title: "Apply for social housing", desc: "Submit housing request through the same platform" },
      { title: "Upload supporting documents", desc: "ID, income proof, enrollment certificate" },
    ],
    requiredDocs: ["Student ID or enrollment certificate", "National ID", "Parents' income tax notices", "RIB", "Proof of address"],
    officialLink: "https://www.messervices.etudiant.gouv.fr",
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "danger", icon: "alert-circle", message: "DZ-4: Driver license renewal due in 3 days", time: "2 hours ago", read: false },
  { id: "n2", type: "warning", icon: "clock", message: "DZ-1: CAF renewal deadline in 10 days", time: "5 hours ago", read: false },
  { id: "n3", type: "information", icon: "file-warning", message: "DZ-6: Missing income proof document", time: "1 day ago", read: false },
  { id: "n4", type: "success", icon: "check-circle-2", message: "DZ-2: Carte vitale application completed", time: "3 days ago", read: true },
];
